
MAX_WAIT_FOR_PID = 10
PID_INTERVAL = 1
COLLECTOR_KEEPALIVE_INTERVAL = 5
MAX_WAIT_FOR_STATUS = 5 * 60
MAX_WAIT_FOR_DELETION = 5 * 60
MAX_WAIT_FOR_ISOLATE = 2 * 60

MAX_WAIT_FOR_NEW_CONFIG_FILE_TO_APPEAR = 3 * 60
CONFIG_FILE_APPEAR_INTERVAL = 2
