from enum import Enum


class UserRoles(Enum):
    USER = 'User'
    ADMIN = 'Admin'
    LOCAL_ADMIN = 'Local Admin'
    REST_API = 'Rest API'


class SystemState(Enum):
    RUNNING = 'RUNNING'
    NOT_RUNNING = 'NOT_RUNNING'
    DISCONNECTED = 'DISCONNECTED'
    DOWN = 'DOWN'


class ComponentType(Enum):
    MANAGEMENT = 'manager'
    BOTH = 'both'
    AGGREGATOR = 'aggregator'
    CORE = 'core'


class OsTypeEnum(Enum):
    WINDOWS = 'WINDOWS'
    LINUX = 'LINUX'
    OS_X = 'OS_X'


class CollectorTypes(Enum):
    WINDOWS_11_64 = 'WINDOWS_11_64'
    WINDOWS_10_32 = 'WINDOWS_10_32'
    WINDOWS_10_64 = 'WINDOWS_10_64'
    WINDOWS_8_64 = 'WINDOWS_8_64'
    WINDOWS_7_64 = 'WINDOWS_7_64'
    WINDOWS_7_32 = 'WINDOWS_7_32'
    WIN_SERVER_2016 = 'WIN_SERVER_2016'
    WIN_SERVER_2019 = 'WIN_SERVER_2019'
    LINUX_CENTOS_6 = 'LINUX_CENTOS_6'
    LINUX_CENTOS_7 = 'LINUX_CENTOS_7'
    LINUX_CENTOS_8 = 'LINUX_CENTOS_8'
    LINUX_UBUNTU_16 = 'LINUX_UBUNTU_16'
    LINUX_UBUNTU_18 = 'LINUX_UBUNTU_18'
    LINUX_UBUNTU_20 = 'LINUX_UBUNTU_20'


class CollectorTemplateNames(Enum):
    # A Confluence page with updated template names should be followed:
    # http://confluence.ensilo.local/display/QA/Templates+and+preinstalled+application
    WIN_11X64 = 'AUTO_TEMPLATE_WIN_11'
    WIN10_X64H2 = 'AUTO_TEMPLATE_WIN_10_64H2'
    WIN10_X64 = 'AUTO_TEMPLATE_WIN_10_64'
    WIN10_X32 = 'AUTO_TEMPLATE_WIN_10_32'
    WIN81_X64 = 'AUTO_TEMPLATE_WIN_81_64'
    WIN81_X32 = 'AUTO_TEMPLATE_WIN_81_32'
    WIN7_X64 = 'AUTO_TEMPLATE_WIN_7_64'
    WIN7_X86 = 'AUTO_TEMPLATE_WIN_7_86'

    WIN_SERV_2012 = 'AUTO_TEMPLATE_WIN_SERV_2012'
    WIN_SERV_2016 = 'AUTO_TEMPLATE_WIN_SERV_2016'
    WIN_SERV_2019 = 'AUTO_TEMPLATE_WIN_SERV_2019'
    WIN_SERV_2020 = 'AUTO_TEMPLATE_WIN_SERV_2020'
    WIN_SERV_2022 = 'AUTO_TEMPLATE_WIN_SERV_2022'

    LINUX_CENTOS_6 = 'TEMPLATE_CENTOS_6'
    LINUX_CENTOS_7 = 'TEMPLATE_CENTOS_7'
    LINUX_CENTOS_8 = 'TEMPLATE_CENTOS_8'
    LINUX_UBUNTU_16 = 'TEMPLATE_UBUNTU_16'
    LINUX_UBUNTU_18 = 'TEMPLATE_UBUNTU_18'
    LINUX_UBUNTU_20 = 'TEMPLATE_UBUNTU_20'
    LINUX_AMAZON = 'TEMPLATE__VT41_AMAZON'
    LINUX_ORACLE_77 = 'TEMPLATE_VT41_ORACLE_7.7'
    LINUX_ORACLE_80 = 'TEMPLATE_VT41_ORACLE_8_0'
    LINUX_ORACLE_81 = 'TEMPLATE_VT41_ORACLE_8_1'
    LINUX_ORACLE_82 = 'TEMPLATE_VT41_ORACLE_8.2'
    LINUX_ORACLE_83 = 'TEMPLATE_VT41_ORACLE_8.3'
    LINUX_SUSE = 'TEMPLATE_VT41_SUSE'


class HttpRequestMethodsEnum(Enum):
    GET = 'GET'
    HEAD = 'HEAD'
    POST = 'POST'
    PUT = 'PUT'
    DELETE = 'DELETE'
    CONNECT = 'CONNECT'
    TRACE = 'TRACT'
    OPTIONS = 'OPTIONS'


class ManagementUserRoles(Enum):
    ROLE_REST_API = 'ROLE_REST_API'
    ROLE_USER = 'ROLE_USER'
    ROLE_ADMIN = 'ROLE_ADMIN'
    ROLE_HOSTER = 'ROLE_HOSTER'


class LinuxDistroTypes(Enum):
    UBUNTU = 'UBUNTU'
    CENTOS = 'CENTOS'
