import json
from enum import Enum

import allure
import requests

import third_party_details
from infra.allure_report_handler.reporter import Reporter
from infra.system_components.management import Management


class JiraConfiguration:

    endpoint = 'http://jira.ensilo.local'
    user_name = third_party_details.USER_NAME
    password = third_party_details.PASSWORD
    project = 'EN'


class TestStatusEnum(Enum):
    PASS = 'PASS'
    FAIL = 'FAIL'
    ABORTED = 'ABORTED'


class JiraXrayHandler:

    def __init__(self, mark: str, management: Management):
        self.base_url = JiraConfiguration.endpoint
        self.execution_key = None
        self.mark = mark
        self.auth = (JiraConfiguration.user_name, JiraConfiguration.password)
        self.headers = {
            'Content-Type': 'application/json'
        }
        self.management = management

    def publish_test_result(self, test_key, status: TestStatusEnum):
        test = dict(testKey=test_key, status=status.value)
        execution_key = self.get_execution_key()
        data = dict(testExecutionKey=execution_key, tests=[test])
        data_as_json = json.dumps(data)
        endpoint = f'{self.base_url}/rest/raven/2.0/import/execution'
        try:
            response = requests.post(url=endpoint, headers=self.headers, data=data_as_json, auth=self.auth, verify=False)
            if not 200 <= response.status_code < 300:
                content = None
                try:
                    content = json.loads(response.content)
                finally:
                    assert False, f"Failed to publish test reults to Jira, test_key: {test}, statuse code: {response.status_code}, response content: {content}"
        except requests.exceptions.ConnectionError as e:
            Reporter.report('Fail to publish test result to Jira')
            raise e

    def get_execution_key(self):
        if self.execution_key is None:
            self.execution_key = self.create_test_execution()

        return self.execution_key

    @allure.step("Create test execution in Jira")
    def create_test_execution(self):
        summary = 'Created by automation'

        collector_os_architecture = self.management.collectors[0].os_station.os_architecture.replace(' ', '-')
        collector_os_version = self.management.collectors[0].os_station.os_version.replace(' ', '-')
        collector_os_name = self.management.collectors[0].os_station.os_name.replace(' ', '-')

        management_version = None
        core_version = None
        collector_version = None
        try:
            management_version = self.management.get_version()
            core_version = self.management.cores[0].get_version()
            collector_version = self.management.collectors[0].get_version()

        except Exception as e:
            pass

        fields = {
            'fields': {
                'project': {'key': JiraConfiguration.project},
                'issuetype': {'name': "Test Execution"},
                'summary': summary,
                'labels': ['automation_regression_ng', self.mark],
                'description': f'automatically generated by the automation, report: {third_party_details.JENKINS_JOB}',
                # 'fixVersions':  [{"add" : {"name" : "release_TEST"}}],
                'assignee': {'name': JiraConfiguration.user_name},
                'customfield_11324': [f'{collector_os_name}_{collector_os_architecture}'], # Test environments
                'customfield_11326': ['EN-73386'], # Test Plan (master test plan for automation purposes)
                # 'customfield_12500': 'place_holder', # collector name
                'customfield_12413': collector_version, # collector version
                'customfield_12414': core_version, # core version
                'customfield_12415': management_version, # management version
                'customfield_12502': [collector_os_architecture, collector_os_version, collector_os_name], # collector type
            }
        }
        data_as_json = json.dumps(fields)
        endpoint = f'{self.base_url}/rest/api/latest/issue'
        response = requests.post(url=endpoint, headers=self.headers, data=data_as_json, auth=self.auth, verify=False)
        if not 200 <= response.status_code < 300:
            content = None
            try:
                content = json.loads(response.content)
            finally:
                assert False, f"Failed to create test execution in Jira, statuse code: {response.status_code}, response content: {content}"

        return json.loads(response.content).get('key')
